(ns client-portal-web-api.specs.inline-response-200-5
  (:require [clojure.spec.alpha :as s]
            [spec-tools.data-spec :as ds]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            [client-portal-web-api.specs.summary :refer :all]
            )
  (:import (java.io File)))


(def inline-response-200-5-data
  {
   (ds/opt :accountready) summary-spec
   (ds/opt :accounttype) summary-spec
   (ds/opt :accruedcash) summary-spec
   (ds/opt :accruedcash-c) summary-spec
   (ds/opt :accruedcash-f) summary-spec
   (ds/opt :accruedcash-s) summary-spec
   (ds/opt :accrueddividend) summary-spec
   (ds/opt :accrueddividend-c) summary-spec
   (ds/opt :accrueddividend-f) summary-spec
   (ds/opt :accrueddividend-s) summary-spec
   (ds/opt :availablefunds) summary-spec
   (ds/opt :availablefunds-c) summary-spec
   (ds/opt :availablefunds-f) summary-spec
   (ds/opt :availablefunds-s) summary-spec
   (ds/opt :billable) summary-spec
   (ds/opt :billable-c) summary-spec
   (ds/opt :billable-f) summary-spec
   (ds/opt :billable-s) summary-spec
   (ds/opt :buyingpower) summary-spec
   (ds/opt :cushion) summary-spec
   (ds/opt :daytradesremaining) summary-spec
   (ds/opt :daytradesremainingt1) summary-spec
   (ds/opt :daytradesremainingt2) summary-spec
   (ds/opt :daytradesremainingt3) summary-spec
   (ds/opt :daytradesremainingt4) summary-spec
   (ds/opt :equitywithloanvalue) summary-spec
   (ds/opt :equitywithloanvalue-c) summary-spec
   (ds/opt :equitywithloanvalue-f) summary-spec
   (ds/opt :equitywithloanvalue-s) summary-spec
   (ds/opt :excessliquidity) summary-spec
   (ds/opt :excessliquidity-c) summary-spec
   (ds/opt :excessliquidity-f) summary-spec
   (ds/opt :excessliquidity-s) summary-spec
   (ds/opt :fullavailablefunds) summary-spec
   (ds/opt :fullavailablefunds-c) summary-spec
   (ds/opt :fullavailablefunds-f) summary-spec
   (ds/opt :fullavailablefunds-s) summary-spec
   (ds/opt :fullexcessliquidity) summary-spec
   (ds/opt :fullexcessliquidity-c) summary-spec
   (ds/opt :fullexcessliquidity-f) summary-spec
   (ds/opt :fullexcessliquidity-s) summary-spec
   (ds/opt :fullinitmarginreq) summary-spec
   (ds/opt :fullinitmarginreq-c) summary-spec
   (ds/opt :fullinitmarginreq-f) summary-spec
   (ds/opt :fullinitmarginreq-s) summary-spec
   (ds/opt :fullmaintmarginreq) summary-spec
   (ds/opt :fullmaintmarginreq-c) summary-spec
   (ds/opt :fullmaintmarginreq-f) summary-spec
   (ds/opt :fullmaintmarginreq-s) summary-spec
   (ds/opt :grosspositionvalue) summary-spec
   (ds/opt :grosspositionvalue-c) summary-spec
   (ds/opt :grosspositionvalue-f) summary-spec
   (ds/opt :grosspositionvalue-s) summary-spec
   (ds/opt :guarantee) summary-spec
   (ds/opt :guarantee-c) summary-spec
   (ds/opt :guarantee-f) summary-spec
   (ds/opt :guarantee-s) summary-spec
   (ds/opt :highestseverity) summary-spec
   (ds/opt :highestseverity-c) summary-spec
   (ds/opt :highestseverity-f) summary-spec
   (ds/opt :highestseverity-s) summary-spec
   (ds/opt :indianstockhaircut) summary-spec
   (ds/opt :indianstockhaircut-c) summary-spec
   (ds/opt :indianstockhaircut-f) summary-spec
   (ds/opt :indianstockhaircut-s) summary-spec
   (ds/opt :initmarginreq) summary-spec
   (ds/opt :initmarginreq-c) summary-spec
   (ds/opt :initmarginreq-f) summary-spec
   (ds/opt :initmarginreq-s) summary-spec
   (ds/opt :leverage) summary-spec
   (ds/opt :leverage-c) summary-spec
   (ds/opt :leverage-f) summary-spec
   (ds/opt :leverage-s) summary-spec
   (ds/opt :lookaheadavailablefunds) summary-spec
   (ds/opt :lookaheadavailablefunds-c) summary-spec
   (ds/opt :lookaheadavailablefunds-f) summary-spec
   (ds/opt :lookaheadavailablefunds-s) summary-spec
   (ds/opt :lookaheadexcessliquidity) summary-spec
   (ds/opt :lookaheadexcessliquidity-c) summary-spec
   (ds/opt :lookaheadexcessliquidity-f) summary-spec
   (ds/opt :lookaheadexcessliquidity-s) summary-spec
   (ds/opt :lookaheadinitmarginreq) summary-spec
   (ds/opt :lookaheadinitmarginreq-c) summary-spec
   (ds/opt :lookaheadinitmarginreq-f) summary-spec
   (ds/opt :lookaheadinitmarginreq-s) summary-spec
   (ds/opt :lookaheadmaintmarginreq) summary-spec
   (ds/opt :lookaheadmaintmarginreq-c) summary-spec
   (ds/opt :lookaheadmaintmarginreq-f) summary-spec
   (ds/opt :lookaheadmaintmarginreq-s) summary-spec
   (ds/opt :lookaheadnextchange) summary-spec
   (ds/opt :maintmarginreq) summary-spec
   (ds/opt :maintmarginreq-c) summary-spec
   (ds/opt :maintmarginreq-f) summary-spec
   (ds/opt :maintmarginreq-s) summary-spec
   (ds/opt :netliquidation) summary-spec
   (ds/opt :netliquidation-c) summary-spec
   (ds/opt :netliquidation-f) summary-spec
   (ds/opt :netliquidation-s) summary-spec
   (ds/opt :netliquidationuncertainty) summary-spec
   (ds/opt :nlvandmargininreview) summary-spec
   (ds/opt :pasharesvalue) summary-spec
   (ds/opt :pasharesvalue-c) summary-spec
   (ds/opt :pasharesvalue-f) summary-spec
   (ds/opt :pasharesvalue-s) summary-spec
   (ds/opt :postexpirationexcess) summary-spec
   (ds/opt :postexpirationexcess-c) summary-spec
   (ds/opt :postexpirationexcess-f) summary-spec
   (ds/opt :postexpirationexcess-s) summary-spec
   (ds/opt :postexpirationmargin) summary-spec
   (ds/opt :postexpirationmargin-c) summary-spec
   (ds/opt :postexpirationmargin-f) summary-spec
   (ds/opt :postexpirationmargin-s) summary-spec
   (ds/opt :previousdayequitywithloanvalue) summary-spec
   (ds/opt :previousdayequitywithloanvalue-c) summary-spec
   (ds/opt :previousdayequitywithloanvalue-f) summary-spec
   (ds/opt :previousdayequitywithloanvalue-s) summary-spec
   (ds/opt :segmenttitle-c) summary-spec
   (ds/opt :segmenttitle-f) summary-spec
   (ds/opt :segmenttitle-s) summary-spec
   (ds/opt :totalcashvalue) summary-spec
   (ds/opt :totalcashvalue-c) summary-spec
   (ds/opt :totalcashvalue-f) summary-spec
   (ds/opt :totalcashvalue-s) summary-spec
   (ds/opt :totaldebitcardpendingcharges) summary-spec
   (ds/opt :totaldebitcardpendingcharges-c) summary-spec
   (ds/opt :totaldebitcardpendingcharges-f) summary-spec
   (ds/opt :totaldebitcardpendingcharges-s) summary-spec
   (ds/opt :tradingtype-f) summary-spec
   (ds/opt :tradingtype-s) summary-spec
   })

(def inline-response-200-5-spec
  (ds/spec
    {:name ::inline-response-200-5
     :spec inline-response-200-5-data}))
